.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "HOLA\-SERGIO" "1" "March 2019" "" ""
.
.SH "NAME"
\fBhola\-sergio\fR \- the first gem of s\-e\-r\-g\-i\-o
.
.SH "SYNOPSIS"
.
.nf

gem hola
.
.fi
.
.SH "DESCRIPTION"
.
.nf

A simple hello world gem, from a very special man

If you would be a real seeker after truth,
it is necessary that at least once in your life you doubt,
as far as possible, all things
.
.fi
.
.SH "INSTALL"
gem install hola\-sergio
.
.SH "QUICKSTART"
.
.nf

gem hola
.
.fi
.
.SH "THANKS"
.
.IP "\(bu" 4
God
.
.IP "" 0
.
.SH "COPYRIGHT"
hola\-sergio is Copyright (C) 2019 Sergio Romero
.
.SH "SEE ALSO"
\fIhttps://guides\.rubygems\.org/make\-your\-own\-gem/\fR
